services:
  db:
    build:
      context: ./mysql_folder
    image: mysql:8.0.44
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: titanic
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      # Ensures the DB is ready for connections before Python starts
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p0000"]
      interval: 5s
      timeout: 5s
      retries: 10
  python_app:
    build:
      context: ./python_folder
    image: python3_image01
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
volumes:
  mysql_data: